export const CATEGORIES = ['All', 'AI', 'Startups', 'Hardware', 'Software', 'Security', 'Space'];

const NOW = new Date('2026-07-02T12:00:00Z');
export function timeAgo(iso) {
  const diffH = Math.round((NOW - new Date(iso)) / 3600000);
  if (diffH < 1) return 'Just now';
  if (diffH < 24) return diffH + 'h ago';
  return Math.round(diffH / 24) + 'd ago';
}

const RAW_ARTICLES = [
  { category: 'AI', source: { id: 'axios', name: 'Axios' }, author: 'Axios Staff', title: 'UN and ITU Launch AI for Good Global Commission', description: "The United Nations and the International Telecommunication Union have formed a new commission meant to bring tech leaders and heads of state to the same table on AI governance. Its first session is scheduled for July 8 in Geneva. The effort comes as countries pursue increasingly divergent AI rulebooks, from Europe's risk-based regulatory model to more security-driven restrictions in the U.S. and state-backed development in parts of Asia. Organizers hope the forum can help close policy gaps before national approaches drift too far apart to reconcile.", url: 'https://www.axios.com', urlToImage: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80', publishedAt: '2026-07-01T09:00:00Z' },
  { category: 'AI', source: { id: 'reuters', name: 'Reuters' }, author: 'Echo Wang', title: 'SoftBank Reopens Talks on Loan Backed by Its OpenAI Stake', description: 'SoftBank is reportedly in renewed discussions over a loan of roughly $10 billion secured against its stake in OpenAI. Sources say the firm is offering to guarantee repayment if the value of that collateral ends up falling short of the loan amount. The move reflects how large private stakes in frontier AI labs are increasingly being treated as bankable assets, even though those valuations remain largely untested by public markets. Terms of the arrangement have not been finalized.', url: 'https://www.reuters.com', urlToImage: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80', publishedAt: '2026-07-01T11:00:00Z' },
  { category: 'AI', source: { id: 'financial-times', name: 'Financial Times' }, author: 'George Hammond', title: 'White House Nears Voluntary AI Standards Deal With Major Labs', description: 'The White House is said to be in advanced talks with leading AI companies over a set of voluntary standards and release timelines for upcoming frontier models, with an announcement possibly coming within days. The framework would not be legally binding, but it signals a shift toward informal coordination between government and industry on how and when powerful new models reach the public. Details on enforcement, participation, and scope are still being worked out.', url: 'https://www.ft.com', urlToImage: 'https://images.unsplash.com/photo-1591696205602-2f950c417cb9?w=800&q=80', publishedAt: '2026-06-30T16:00:00Z' },
  { category: 'AI', source: { id: 'google-ai', name: 'Google AI Studio' }, author: 'Google Communications', title: 'Google Ships Two New Image-Generation Models While Gemini 3.5 Pro Slips Again', description: "Google released Gemini 3.1 Flash Image and Gemini 3 Pro Image on June 30, giving developers a cheaper, speed-oriented option and a quality-first option for image generation, both available immediately through Google AI Studio and the Gemini API. The releases help round out Google's model lineup while its flagship Gemini 3.5 Pro continues to slip past its promised launch window, with the company citing enterprise feedback about high token consumption in long agentic tasks as the reason for the delay.", url: 'https://ai.google.dev', urlToImage: 'https://images.unsplash.com/photo-1516110833967-0b5716ca1387?w=800&q=80', publishedAt: '2026-06-30T18:00:00Z' },
  { category: 'AI', source: { id: 'theaiinsider', name: 'AI Insider' }, author: 'James Dargan', title: 'Microsoft Launches $2.5B Frontier Company to Drive Enterprise AI Deployments', description: 'Microsoft has stood up a new operating business called Microsoft Frontier Company, backed by $2.5 billion and roughly 6,000 engineering and industry specialists, aimed at helping enterprise customers actually deploy Microsoft\'s AI tools successfully rather than just license them. Executives describe it as a larger, more outcome-driven version of the forward-deployed-engineer teams other AI companies have recently stood up, following similar moves from Amazon Web Services, OpenAI, and Anthropic in the same window.', url: 'https://theaiinsider.tech', urlToImage: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=800&q=80', publishedAt: '2026-07-02T09:00:00Z' },
  { category: 'Startups', source: { id: 'techcrunch', name: 'TechCrunch' }, author: 'Rebecca Bellan', title: 'Robotics Startups Draw Fresh Capital as AV Hype Cycle Returns', description: 'Investors and founders who lived through the first wave of autonomous vehicle startups a decade ago are now pouring money and talent back into robotics. Veterans of that earlier boom, including well-known names from the original self-driving wars, are launching new companies and pulling in significant funding, with the same intense competition for engineering talent that defined the first cycle. The parallels to 2016 are notable enough that people inside the industry are openly drawing the comparison.', url: 'https://techcrunch.com', urlToImage: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80', publishedAt: '2026-07-01T13:00:00Z' },
  { category: 'Startups', source: { id: 'techstartups', name: 'Tech Startups' }, author: 'Tech Startups Staff', title: 'Together AI Closes $800M Series C to Scale Open-Source Model Infrastructure', description: 'Together AI raised an $800 million Series C led by Aramco Ventures, with participation from Nvidia, Salesforce Ventures, and General Catalyst, pushing its valuation to roughly $8.3 billion. The company runs a platform that lets enterprises train and serve AI models built on open-source foundations, positioning it as core infrastructure for organizations that want alternatives to closed frontier labs. The round reflects a broader shift in venture funding toward the compute and infrastructure layer of the AI stack rather than consumer-facing apps.', url: 'https://techstartups.com', urlToImage: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&q=80', publishedAt: '2026-07-01T14:30:00Z' },
  { category: 'Startups', source: { id: 'techstartups', name: 'Tech Startups' }, author: 'Tech Startups Staff', title: 'TwelveLabs Raises $100M Series B for AI Video Understanding', description: 'Video-understanding startup TwelveLabs closed a $100 million Series B co-led by NEA and NAVER Ventures, with Amazon and Radical Ventures also participating, bringing its total funding to about $207 million. The company builds models that let computers search, summarize, and reason over video content the way search engines handle text, a capability increasingly in demand as media, security, and advertising companies look to make sense of massive video libraries.', url: 'https://techstartups.com', urlToImage: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&q=80', publishedAt: '2026-07-01T14:30:00Z' },
  { category: 'Startups', source: { id: 'techstartups', name: 'Tech Startups' }, author: 'Tech Startups Staff', title: 'LeapXpert Lands $180M Growth Round for Enterprise Communications Governance', description: 'LeapXpert, which helps regulated companies govern and archive employee communications across messaging apps, raised a $180 million growth investment led by Riverwood Capital. The jump from a $20 million Series B just last year signals investors now view the company as a category-scale enterprise platform rather than a niche compliance tool, especially as conversation data itself becomes something enterprises want to feed into AI systems responsibly.', url: 'https://techstartups.com', urlToImage: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&q=80', publishedAt: '2026-06-30T20:00:00Z' },
  { category: 'Startups', source: { id: 'business-wire', name: 'Verkada' }, author: 'Verkada Communications', title: 'Verkada and Nvidia Team Up on Physical AI for Security Operations', description: "Security technology startup Verkada announced a collaboration with Nvidia to accelerate development of physical AI for buildings and security operations, with Nvidia also joining as a new investor following a prior strategic investment from Alphabet's CapitalG. The partnership points to growing interest in AI that can reason about the physical world in real time, not just process text or images after the fact, with security and facilities management as an early proving ground.", url: 'https://www.verkada.com', urlToImage: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&q=80', publishedAt: '2026-07-01T10:00:00Z' },
  { category: 'Hardware', source: { id: 'cnbc', name: 'CNBC' }, author: 'CNBC Markets Desk', title: 'Chipmakers Slide as Investors Rotate Out of Tech After Strong First Half', description: 'The Nasdaq fell as semiconductor stocks pulled back sharply, with Micron and Sandisk both dropping more than 10% in a single session despite posting massive year-to-date gains. Nvidia and Broadcom also slipped. The pullback came as investors rotated money toward industrial and blue-chip names after chip stocks collectively surged more than 80% in the first half of 2026, with analysts describing the move as healthy profit-taking rather than a shift in the underlying AI infrastructure story.', url: 'https://www.cnbc.com/technology/', urlToImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80', publishedAt: '2026-07-01T20:00:00Z' },
  { category: 'Hardware', source: { id: 'benzinga', name: 'Benzinga' }, author: 'Benzinga Staff', title: "Musk Says Tesla's Model S and X Lines Now Building Optimus Robots", description: "Elon Musk said production lines previously dedicated to the Model S and Model X sedans have been repurposed to manufacture Tesla's Optimus humanoid robot. The shift suggests Tesla is prioritizing robotics manufacturing capacity over legacy sedan production as it scales up Optimus output, and raises questions about long-term availability of the older vehicle lines for existing customers and service.", url: 'https://www.benzinga.com', urlToImage: 'https://images.unsplash.com/photo-1561144257-e32e8efc6c4f?w=800&q=80', publishedAt: '2026-07-01T12:00:00Z' },
  { category: 'Hardware', source: { id: 'techstartups', name: 'Tech Startups' }, author: 'Tech Startups Staff', title: 'Chip-Design Startup Oxmiq Raises $35M to Merge GPU, CPU, and TPU Into One Block', description: 'Oxmiq, led by former Intel and Apple chip executive Raja Koduri, raised $35 million to develop a licensable silicon design that combines the functions of a GPU, CPU, and tensor accelerator into a single block, aiming to shorten development cycles for companies building custom AI chips. Rather than selling finished chips, Oxmiq licenses blueprints that semiconductor companies and cloud providers can customize, positioning itself as infrastructure for the broader AI hardware buildout rather than a competitor to Nvidia directly.', url: 'https://techstartups.com', urlToImage: 'https://images.unsplash.com/photo-1591405351990-4726e331f141?w=800&q=80', publishedAt: '2026-07-01T14:15:00Z' },
  { category: 'Software', source: { id: 'microsoft-news', name: 'Microsoft' }, author: 'Microsoft Communications', title: 'Microsoft 365 Commercial Pricing Changes Take Effect', description: 'New pricing across several Microsoft 365 Enterprise, Business, Frontline, and Government-equivalent plans took effect July 1. Microsoft says the changes reflect AI, security, and management capabilities that have been added across the suite over the past year. The timing lands as many companies are already reassessing software budgets in light of AI features increasingly being bundled into core productivity tools, effectively turning those features into new pricing leverage for vendors.', url: 'https://www.microsoft.com', urlToImage: 'https://images.unsplash.com/photo-1633419461186-7d40a38105ec?w=800&q=80', publishedAt: '2026-07-01T08:00:00Z' },
  { category: 'Software', source: { id: 'cybernews', name: 'Cybernews' }, author: 'Cybernews Staff', title: 'Microsoft Veteran Rolls Back Years of Changes to Notepad', description: 'A longtime Microsoft engineer has reversed several recent additions to the Windows Notepad app, restoring some of the stripped-down, lightweight feel that longtime users say had been lost as the app gained more features over the past few years. The change reflects a broader tension inside Microsoft between adding modern capabilities to legacy tools and preserving the simplicity that made them useful in the first place.', url: 'https://cybernews.com', urlToImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80', publishedAt: '2026-07-02T06:00:00Z' },
  { category: 'Software', source: { id: 'tech-reader', name: 'AI News Daily' }, author: 'Aaron', title: '$60B All-Stock Deal to Acquire AI Code Editor Cursor Advances Toward Close', description: 'The roughly $60 billion all-stock acquisition of Anysphere, the company behind the popular AI coding editor Cursor, remains on track for a third-quarter regulatory close. The deal would fold one of the fastest-growing developer tools of the past two years into a much larger technology company, at a moment when AI-assisted coding tools are rapidly consolidating and developers are watching closely for how the acquisition might change pricing or product direction.', url: 'https://www.tech-reader.blog', urlToImage: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&q=80', publishedAt: '2026-07-01T07:00:00Z' },
  { category: 'Software', source: { id: 'social-media-today', name: 'Social Media Today' }, author: 'Andrew Hutchinson', title: 'X Launches Live Studio, a Revamped Livestreaming Hub', description: "X rolled out Live Studio, an updated livestreaming hub inside Creator Studio that includes a simplified desktop setup, more granular chat moderation controls, custom thumbnails, and other production features aimed at making live broadcasts easier to manage. The update is part of X's ongoing push to compete more directly with dedicated livestreaming platforms by lowering the technical bar for creators who want to go live natively on the platform.", url: 'https://www.socialmediatoday.com', urlToImage: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=800&q=80', publishedAt: '2026-06-29T12:00:00Z' },
  { category: 'Security', source: { id: 'the-hacker-news', name: 'The Hacker News' }, author: 'The Hacker News', title: 'Adobe Patches Maximum-Severity Flaws in ColdFusion and Campaign Classic', description: 'Adobe released fixes for multiple critical vulnerabilities in ColdFusion and Campaign Classic, several carrying maximum CVSS severity scores. Left unpatched, the flaws could allow arbitrary code execution, privilege escalation, and unauthorized file system access. Security researchers are urging organizations running affected versions to patch immediately given the severity and the fact that ColdFusion servers have historically been a popular target for opportunistic scanning shortly after disclosures like this one.', url: 'https://thehackernews.com', urlToImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80', publishedAt: '2026-07-01T08:00:00Z' },
  { category: 'Security', source: { id: 'the-hacker-news', name: 'The Hacker News' }, author: 'The Hacker News', title: 'Attackers Actively Exploiting Critical Flaw in Progress Kemp LoadMaster', description: "Researchers say a command-injection vulnerability in Progress Kemp LoadMaster, a widely used load balancer appliance, is being actively exploited in the wild, with attempts first spotted in late June. The flaw allows an unauthenticated attacker to run arbitrary commands on affected devices by sending unsanitized input to the appliance's API, and researchers have traced the underlying bug to a specific input-handling function that failed to properly escape user-supplied data.", url: 'https://thehackernews.com', urlToImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80', publishedAt: '2026-06-30T14:00:00Z' },
  { category: 'Security', source: { id: 'cybernews', name: 'Cybernews' }, author: 'Cybernews Staff', title: 'Billions of Phones Exposed by AirDrop and Quick Share Flaws', description: "Researchers disclosed six security flaws affecting Apple's AirDrop and Android's Quick Share file-sharing protocols, which together run on an estimated five billion phones that are constantly listening for nearby file-transfer requests. The flaws could let a nearby attacker crash a target's device, interfere with an active file transfer, or potentially execute code, depending on the specific vulnerability and device configuration. Both companies have been notified and patches are expected to roll out gradually.", url: 'https://cybernews.com', urlToImage: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80', publishedAt: '2026-07-02T05:00:00Z' },
  { category: 'Security', source: { id: 'cybernews', name: 'Cybernews' }, author: 'Cybernews Staff', title: '24 Billion Records Exposed in Colossal Data Leak', description: 'A newly surfaced dataset containing an estimated 24 billion records, including usernames and passwords, has been found exposed online, in what researchers are calling one of the largest credential leaks compiled to date. Much of the data appears to be aggregated from previous breaches rather than a single new incident, but its sheer scale means many of the exposed credentials are likely still valid and reused across other services, raising the risk of large-scale account takeover attempts.', url: 'https://cybernews.com', urlToImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80', publishedAt: '2026-06-23T00:00:00Z' },
  { category: 'Security', source: { id: 'the-hacker-news', name: 'The Hacker News' }, author: 'The Hacker News', title: 'Flaws in AI Code Editor Cursor Could Let a Single Prompt Escape the Sandbox', description: "Security researchers at Cato AI Labs disclosed two vulnerabilities in Cursor, an AI-powered code editor, that could let an ordinary-looking prompt break out of the editor's safety sandbox and run arbitrary commands on a developer's machine. Unlike typical exploits, there is no malicious link to click or approval dialog to ignore, making the flaws, named DuneSlide, notable for how little user interaction they require to trigger.", url: 'https://thehackernews.com', urlToImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80', publishedAt: '2026-07-01T09:00:00Z' },
  { category: 'Space', source: { id: 'scitechdaily', name: 'SciTechDaily' }, author: 'SciTechDaily Staff', title: "Desert Lizard's Movement Inspires New Approach to Mars Rover Mobility", description: "Researchers studying how a Sahara desert lizard moves across loose, shifting sand say their findings could inform more efficient locomotion designs for future Mars rovers navigating fine, granular terrain. The lizard's distinctive sand-swimming motion offers a biological blueprint that engineers hope to translate into rover designs less prone to getting stuck in soft regolith, a problem that has hampered past missions on the Martian surface.", url: 'https://scitechdaily.com', urlToImage: 'https://images.unsplash.com/photo-1614730321146-b6fa6a46bcb4?w=800&q=80', publishedAt: '2026-07-01T10:00:00Z' },
  { category: 'Space', source: { id: 'cnbc', name: 'CNBC' }, author: 'CNBC Markets Desk', title: 'Analyst Starts SpaceX Coverage With Buy Rating on Starship Reusability Bet', description: "A Wall Street analyst initiated formal research coverage of SpaceX with a buy rating and a 12-month price target implying more than 11% upside, describing the company as a 'vertically integrated' business spanning rocket launches, internet connectivity, and computing infrastructure. The analyst pointed to Starship's reusability, still in a test phase as of the most recent milestone, as the backbone connecting those segments and the key driver of long-term cost savings across the business.", url: 'https://www.cnbc.com', urlToImage: 'https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?w=800&q=80', publishedAt: '2026-07-01T15:00:00Z' },
  { category: 'Space', source: { id: 'spaceflightnow', name: 'Spaceflight Now' }, author: 'Spaceflight Now Staff', title: 'Atlas V Rocket Launches Final Batch of Amazon Leo Broadband Satellites', description: "A United Launch Alliance Atlas V rocket launched 29 more Amazon Leo broadband internet satellites into low Earth orbit from Florida early Thursday morning, marking the ninth and final Atlas V mission that Amazon had booked for its satellite constellation. The launch continues Amazon's buildout of a broadband network intended to compete with SpaceX's Starlink, with future launches expected to shift to other rockets now that the Atlas V contract is complete.", url: 'https://spaceflightnow.com', urlToImage: 'https://images.unsplash.com/photo-1516849841032-87cbac4d88f7?w=800&q=80', publishedAt: '2026-07-02T04:24:00Z' },
  { category: 'Space', source: { id: 'nasa-science', name: 'NASA Science' }, author: 'Alise Fisher', title: "Weather Delays Launch of Mission to Boost NASA's Swift Observatory", description: "The launch of Katalyst Space's robotic servicing spacecraft LINK, designed to boost the orbit of NASA's Neil Gehrels Swift Observatory before it re-enters the atmosphere, was postponed again due to unfavorable weather. The mission will fly on Northrop Grumman's Pegasus XL rocket, launched from an aircraft over Kwajalein Atoll in the Marshall Islands, and is notable as the final planned flight of the Pegasus XL, after which no air-launch rocket systems will remain in operation anywhere in the world.", url: 'https://science.nasa.gov', urlToImage: 'https://images.unsplash.com/photo-1446776709462-d6b525c57bd3?w=800&q=80', publishedAt: '2026-07-01T05:06:00Z' },
  { category: 'Space', source: { id: 'nasa', name: 'NASA' }, author: 'NASA Communications', title: 'NASA Announces Artemis III Crew and New Lunar Rover Contracts', description: 'NASA provided new details on its Artemis III mission, announcing the four prime crew members and one backup assigned to the flight, which will attempt one of the most complex human spaceflight missions in recent history. Separately, during a Moon Base event at NASA Headquarters, the agency announced new contracts for crewed lunar terrain vehicles that astronauts will use to explore the lunar surface during upcoming missions.', url: 'https://www.nasa.gov', urlToImage: 'https://images.unsplash.com/photo-1454789548928-9efd52dc4031?w=800&q=80', publishedAt: '2026-06-29T14:00:00Z' },
];

const FEATURED_TITLES = new Set([
  'Microsoft Veteran Rolls Back Years of Changes to Notepad',
  'Billions of Phones Exposed by AirDrop and Quick Share Flaws',
  'Chipmakers Slide as Investors Rotate Out of Tech After Strong First Half',
  'Atlas V Rocket Launches Final Batch of Amazon Leo Broadband Satellites',
]);

function splitSentences(text) {
  return text.match(/[^.!?]+[.!?]+(?:\s|$)/g)?.map((s) => s.trim()) || [text];
}

export const ARTICLES = RAW_ARTICLES.map((a, i) => {
  const sentences = splitSentences(a.description);
  const dek = sentences[0] || a.description;
  const rest = sentences.slice(1);
  const body = [];
  for (let j = 0; j < rest.length; j += 2) body.push(rest.slice(j, j + 2).join(' '));
  return {
    id: i + 1,
    category: a.category,
    featured: FEATURED_TITLES.has(a.title),
    title: a.title,
    dek,
    author: a.source.name,
    time: timeAgo(a.publishedAt),
    readMins: Math.max(2, Math.round(a.description.length / 220) + 2),
    image: a.urlToImage,
    body: body.length ? body : [dek],
  };
});
